---
- hosts: webservers
  become: true
  become_user: root
  vars:
   repo_path: https://github.com/hapawar/Sample_html.git
   dest_path: /var/www/html
  tasks:
  - name: Install httpd
    yum: name=httpd state=present
  - name: Start httpd service
    service: name=httpd state=started
  - name: Clone source code git repo
    git:
        repo: '{{repo_path}}'
        dest: '{{dest_path}}'
        force: yes
