# This playbook will demonstrate the use of ansible galaxy 
# befor executing this playbook you need to download and install target roles from galaxy on master node.
# command: sudo ansible-galaxy install --roles-path /etc/ansible/roles geerlingguy.jenkins geerlingguy.java
---
- hosts: webservers
  become: true
  become_user: root
  vars: 
   jenkins_hostname: localhost
  roles:
    - geerlingguy.java
    - geerlingguy.jenkins