#this playbook shows the usecase of tags in ansible
#when you run ansible playbook by passing tag, only that specific task will run and all other tasks will be skipped.
---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: find uptime
    command: uptime
    register: uptime
    tags: Harish
  - name: find disk usage
    command: df -h
  - name: Print uptime
    debug:
     msg: "The uptime of server is {{uptime}}"
    tags: Harish
